name: Plugins

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  softposit:
    name: "Plugin tests (Posits)"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.11
        with:
          version: "8.14"
      - name: Install Rust compiler
        uses: dtolnay/rust-toolchain@stable
        with:
            toolchain: stable
            components: rustfmt, clippy
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: make install
      - name: "Run posit benchmarks"
        run: racket infra/ci.rkt --platform softposit --precision posit16 --seed 0 infra/bench/posits.fpcore
