name: Integration tests

on: [push]

env:
  RUST_BACKTRACE: full

jobs:
  hamming:
    name: "Integration tests (Hamming)"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        racket-version: [ '8.0', '8.7' ]
        precision: [ 'binary32', 'binary64' ]
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.9
        with:
          version: ${{ matrix.racket-version }}
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: make install
      - run: racket infra/travis.rkt --precision ${{ matrix.precision }} --seed 0 bench/hamming/

  determinism:
    name: "Determinism tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Install Packages"
        run: sudo apt-get install -y libmpfr6 libmpfr-dev
      - name: "Install Racket"
        uses: Bogdanp/setup-racket@v1.9
        with:
          version: 8.7
      - name: Install Rust compiler
        uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: stable
            default: true
            override: true
            components: rustfmt, clippy
      - uses: actions/checkout@master
      - name: "Install dependencies"
        run: make install
      - name: "Run (1st time)"
        run: racket src/herbie.rkt report --threads yes --seed 1 bench/hamming graphs0
      - name: "Run (2nd time)"
        run: racket src/herbie.rkt report --threads yes --seed 1 bench/hamming graphs1
      - name: "Check for determinism"
        run: racket infra/diff.rkt graphs0 graphs1
